
services:

  db:
    image: postgres:latest
    hostname: postgres_db
    env_file:
      - database.env
    ports:
      - "6543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
